apiVersion: apps/v1
kind: Deployment
metadata:
  name: panda-grafana
  namespace: panda-panda
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: panda
      app.kubernetes.io/name: grafana
  template:
    spec:
      containers:
        - name: panda-grafana
          volumeMounts:
            - mountPath: /opt/bitnami/grafana/conf/provisioning/datasources/datasources.yaml
              name: grafana-datasources-conf-map
              subPath: datasources.yaml
      volumes:
      - configMap:
          name: panda-grafana-datasources
        name: grafana-datasources-conf-map