apiVersion: v1
kind: Service
metadata:
  name: {{ include "panda.fullname" . }}-panda-service-service
  labels:
    {{- include "panda.labels" . | nindent 4 }}
    panda/component: panda-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "panda.selectorLabels" . | nindent 4 }}
    panda/component: panda-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "panda.fullname" . }}-panda-service
  labels:
    {{- include "panda.labels" . | nindent 4 }}
    panda/component: panda-service
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "panda.selectorLabels" . | nindent 6 }}
      panda/component: panda-service
  template:
    metadata:
      labels:
        {{- include "panda.selectorLabels" . | nindent 8 }}
        panda/component: panda-service
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-panda-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryBase }}/cit-dev/mes/panda/mm.panda.service:latest"
          imagePullPolicy: Always
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ExternalQueueType
            value: InMemory
          - name: Influx__Database
            value: panda
          - name: Influx__Password
            value: {{ .Values.influxdb.adminUser.pwd }}
          - name: Influx__Url
            value: http://panda-influxdb:8086
          - name: Influx__Username
            value: {{ .Values.influxdb.adminUser.name }}
          - name: MariaDbConnectionString
            value: Server=panda-mariadb-galera;Database={{ index .Values "mariadb-galera" "db" "name" }};Uid=root;Pwd={{ index .Values "mariadb-galera" "rootUser" "password" }};
          - name: MigrationOptions__TableMigrationMode
            value: {{ .Values.panda.migrationOptions.tableMigrationMode }}
          - name: MigrationOptions__SeedType
            value: {{ .Values.panda.migrationOptions.seedType }}
          - name: MigrationOptions__SeedMode
            value: {{ .Values.panda.migrationOptions.seedMode }}
          - name: MigrationOptions__OldDatabaseConnectionString
            value: {{ .Values.panda.migrationOptions.oldDatabaseConnectionString }}
          - name: ExternalQueueType
            value: {{ .Values.panda.externalQueueType }}
          - name: Rabbit__RabitUserName
            value: {{ .Values.panda.rabbit.rabbitUserName }}
          - name: Rabbit__RabbitPassword
            value: {{ .Values.panda.rabbit.rabbitPassword }}
          - name: Rabbit__RabbitHostName
            value: {{ .Values.panda.rabbit.rabbitHostName }}
          - name: Rabbit__VHost
            value: {{ .Values.panda.rabbit.vHost }}
          - name: Rabbit__RabbitPort
            value: {{ .Values.panda.rabbit.rabbitPort }}
          - name: Rabbit__ExchangeName
            value: {{ .Values.panda.rabbit.exchangeName }}
          - name: Rabbit__RouteKey
            value: {{ .Values.panda.rabbit.routeKey }}
          - name: Rabbit__QueueName
            value: {{ .Values.panda.rabbit.queueName }}

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}