#{{-  $url := printf "%s%s" "http://influxdb." .Values.panda.zooUrl -}}

{{- define "panda-grafana-datasources-content" }}
apiVersion: 1
datasources:
  - name: PANDA
    type: influxdb
    org_id: 1
    url: http://influxdb.{{ .Values.panda.zooUrl }}
    user: admin
    database: panda
    basicAuth: true
    basicAuthUser: admin
    withCredentials: true
    isDefault: true
    editable: false
    secureJsonData: {
      basicAuthPassword: "admin",
      password: "admin"
    }
{{- end }}

#apiVersion: v2
#kind: ConfigMap
#metadata:
#  namespace: {{.Release.Namespace}}
#  name: panda-influx-secret
#type: Opaque
#data:
#  name: {{ "PANDA" | b64enc }}
#  url: {{ $url | b64enc }}
#  type: {{ "InfluxDB" | b64enc }}
#  password: {{ "admin" | b64enc }}
#  user: {{ "admin" | b64enc }}
#  database: {{ "panda" | b64enc }}
#  basicAuth: {{ "true" | b64enc }}
#  basicAuthUser: {{ "admin" | b64enc }}
#  basicAuthPassword: {{ "admin" | b64enc }}
#  withCredentials: {{ "true" | b64enc }}
#  isDefault: {{ "true" | b64enc }}
#  editable: {{ "false" | b64enc }}


# Source: mychart/templates/configmap.yaml
apiVersion: v2
kind: ConfigMap
metadata:
  namespace: {{.Release.Namespace}}
  name: panda-grafana-datasources
data:
apiVersion: v2
data:
  datasources.yaml: {{ (include "panda-grafana-datasources-content" .) | trim | quote }}