{{- $fullName := include "panda.fullname" . -}}
apiVersion: extensions/v2
kind: Ingress
metadata:
  name: {{ $fullName }}-panda-influxdb
  labels:
    {{- include "panda.labels" . | nindent 4 }}
    panda/component: panda-influxdb
spec:
  rules:
    - host: influxdb.{{ .Values.panda.zooUrl }}
      http:
        paths:
          - path:
            backend:
              serviceName: {{ $fullName }}-influxdb
              servicePort: 8086
