{{-  $url := printf "%s%s" "http://influxdb." .Values.panda.zooUrl -}}
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  namespace: {{.Release.Namespace}}
#  name: panda-influx-secret
#type: Opaque
#data:
#  name: {{ "PANDA" | b64enc }}
#  url: {{ $url | b64enc }}
#  type: {{ "InfluxDB" | b64enc }}
#  password: {{ "admin" | b64enc }}
#  user: {{ "admin" | b64enc }}
#  database: {{ "panda" | b64enc }}
#  basicAuth: {{ "true" | b64enc }}
#  basicAuthUser: {{ "admin" | b64enc }}
#  basicAuthPassword: {{ "admin" | b64enc }}
#  withCredentials: {{ "true" | b64enc }}
#  isDefault: {{ "true" | b64enc }}
#  editable: {{ "false" | b64enc }}


# Source: mychart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{.Release.Namespace}}
  name: panda-grafana-datasources
data:
apiVersion: v1
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: PANDA
        type: InfluxDB
        orgId: 1
        url: $url
        password: admin
        user: admin
        database: panda
        basicAuth: true
        basicAuthUser: admin
        basicAuthPassword: admin
        withCredentials: true
        isDefault:
        editable: false