{{- $fullName := include "panda.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-panda-service
  labels:
    {{- include "panda.labels" . | nindent 4 }}
    panda/component: panda-service
  annotations:
    cert-manager.io/cluster-issuer: mm-acme
spec:
  rules:
    - host: panda.{{ .Values.panda.zooUrl }}
      http:
        paths:
          - path: /service
            backend:
              serviceName: {{ $fullName }}-panda-service-service
              servicePort: 80
  tls:
  - hosts:
    - panda.{{ .Values.panda.zooUrl }}
    secretName: panda.{{ .Values.panda.zooUrl }}