apiVersion: v1
kind: Service
metadata:
  name: {{ include "panda.fullname" . }}-panda-api-service
  labels:
    {{- include "panda.labels" . | nindent 4 }}
    panda/component: panda-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "panda.selectorLabels" . | nindent 4 }}
    panda/component: panda-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "panda.fullname" . }}-panda-api
  namespace: panda
  labels:
    {{- include "panda.labels" . | nindent 4 }}
    panda/component: panda-api
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "panda.selectorLabels" . | nindent 6 }}
      panda/component: panda-api
  template:
    metadata:
      labels:
        {{- include "panda.selectorLabels" . | nindent 8 }}
        panda/component: panda-api
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-panda-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryBase }}/cit-dev/mes/panda/mm.panda.api:latest"
          imagePullPolicy: Always
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: Influx__Database
            value: panda
          - name: Influx__Password
            value: {{ .Values.influxdb.adminUser.pwd }}
          - name: Influx__Url
            value: http://{{ .Values.panda.baseUrl }}/influxdb
          - name: Influx__Username
            value: {{ .Values.influxdb.adminUser.name }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}