{{- $fullName := include "panda.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-panda-grafana
  labels:
    {{- include "panda.labels" . | nindent 4 }}
    panda/component: panda-grafana
  annotations:
    cert-manager.io/cluster-issuer: "mm-acme"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: grafana.{{ .Values.panda.zooUrl }}
      http:
        paths:
          - path: 
            backend:
              serviceName: {{ $fullName }}-grafana
              servicePort: 3000
