{{- $fullName := include "panda.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-panda-webapp
  labels:
    {{- include "panda.labels" . | nindent 4 }}
    panda/component: panda-webapp
  annotations:
    cert-manager.io/cluster-issuer: mm-acme
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: panda.{{ .Values.panda.zooUrl }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-panda-webapp-service
              servicePort: 80
  tls:
  - hosts:
    - panda.{{ .Values.panda.zooUrl }}
  secretName: panda.{{ .Values.panda.zooUrl }}