{{- $fullName := include "panda.fullname" . -}}
apiVersion: extensions/v2
kind: Ingress
metadata:
  name: {{ $fullName }}-panda-api
  labels:
    {{- include "panda.labels" . | nindent 4 }}
    panda/component: panda-api
spec:
  rules:
    - host: panda.{{ .Values.panda.zooUrl }}
      http:
        paths:
          - path: /api
            backend:
              serviceName: {{ $fullName }}-panda-api-service
              servicePort: 80
