apiVersion: v2
name: infra
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.56

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0

icon: https://www.mm-packaging.com/typo3conf/ext/bb_boilerplate/Resources/Public/Images/logo-packaging.svg

dependencies:
- name: portal
  version: 0.1.83
  repository: https://vandenbergen.github.io/rancher-helm-chart
  namespace: infra-portal
- name: logstash
  version: 2.4.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  namespace: infra-logstash
- name: rabbitmq-ha
  version: 1.44.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  namespace: monitoring
- name: filebeat
  version: 4.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  namespace: infra-filebeat
- name: minio
  version: 5.0.26
  repository: https://kubernetes-charts.storage.googleapis.com/
  namespace: infra-minio