{{- $fullName := include "workflow-manager.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-phpmyadmin
  labels:
    {{- include "workflow-manager.labels" . | nindent 4 }}
    workflow-manager/component: phpmyadmin
spec:
  rules:
    - host: {{ $fullName }}-phpmyadmin.{{ .Values.workflowmanager.zooUrl }}
      http:
        paths:
          - path:
            backend:
              serviceName: {{ $fullName }}-phpmyadmin
              servicePort: 8080
