apiVersion: v1
kind: Service
metadata:
  name: {{ include "workflow-manager.fullname" . }}-rabbitmq
  labels:
    {{- include "workflow-manager.labels" . | nindent 4 }}
    workflow-manager/component: rabbitmq
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "workflow-manager.selectorLabels" . | nindent 4 }}
    workflow-manager/component: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workflow-manager.fullname" . }}-rabbitmq
  labels:
    {{- include "workflow-manager.labels" . | nindent 4 }}
    workflow-manager/component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "workflow-manager.selectorLabels" . | nindent 6 }}
      workflow-manager/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "workflow-manager.selectorLabels" . | nindent 8 }}
        workflow-manager/component: rabbitmq
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-rabbitmq
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "docker.io/bitnami/rabbitmq:3.8.5-debian-10-r38"
          imagePullPolicy: Always
          env:
          - name: RABBITMQ_DEFAULT_USER
            value: "geust"
          - name: RABBITMQ_DEFAULT_PASS
            value: "geust"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}