{{- $fullName := include "workflow-manager.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-workflow-manager-webapp
  labels:
    {{- include "workflow-manager.labels" . | nindent 4 }}
    workflow-manager/component: workflow-manager-webapp
spec:
  rules:
    - host: workflow.{{ .Values.workflowmanager.zooUrl }}
      http:
        paths:
          - path:
            backend:
              serviceName: {{ $fullName }}-workflow-manager-webapp
              servicePort: 80
