apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "portal.fullname" . }}-authenticator-conf
  labels:
    {{- include "portal.labels" . | nindent 4 }}
data:
  appsettings.Production.json: |-
    {
      "Serilog": {
        "MinimumLevel": "Information",
        "WriteTo": [
          {
            "Name": "Console",
            "Args": { "outputTemplate": "[{Timestamp:HH:mm:ss.fff}] {Level:u3} - {Message}{NewLine}{Exception}" }
          },
          {
            "Name": "RollingFile",
            "Args": {
              "pathFormat": "Logs\\log-{Date}.log",
              "outputTemplate": "[{Timestamp:dd/MM/yy HH:mm:ss.fff z}] {Level:u3} {Message}{NewLine}{Exception}"
            }
          }
        ],
        "Enrich": [ "FromLogContext" ]
      },
      "Database": {
        "Name": "{{ index .Values "mariadb-galera" "db" "name" }}",
        "Host": "{{ .Values.portal.dbHost }}",
        "Port": 3306,
        "User": "root",
        "Password": "{{ index .Values "mariadb-galera" "rootUser" "password" }}"
      },
      "Identity": {
        "DefaultUserName": "root",
        "DefaultPassword": "Root#123",
        "JwtIssuer": "https://portal.{{ .Values.portal.zooUrl }}/authenticator",
        "Roles": [
          "User",
          "Admin",
          "Manager"
        ],
        "Clients": [
          {
            "ClientId": "portal",
            "ClientName": "portalMenu",
            "AllowedGrantTypes": [ "authorization_code" ],
            "RedirectUris": [
              "https://portal.{{ .Values.portal.zooUrl }}/assets/silent-refresh.html",
              "https://portal.{{ .Values.portal.zooUrl }}/main"
            ],
            "PostLogoutRedirectUris": [
              "https://portal.{{ .Values.portal.zooUrl }}/main"
            ],
            "AllowedScopes": [
              "openid",
              "profile",
              "email",
              "api",
              "roles",
              "account"
            ],
            "RequirePkce": true,
            "RequireConsent": false,
            "RequireClientSecret": false,
            "AccessTokenLifetime": 7200,
            "IdentityTokenLifetime": 7200
          },  
          {
            "ClientId": "grafana",
            "ClientName": "GrafanaUI",
            "AllowedGrantTypes": [ "authorization_code" ],
            "RedirectUris": [
              "https://grafana.{{ .Values.portal.zooUrl }}/login/generic_oauth",
              "https://grafana.{{ .Values.portal.zooUrl }}/login"
            ],
            "PostLogoutRedirectUris": [
              "https://grafana.{{ .Values.portal.zooUrl }}/login"
            ],
            "AllowedScopes": [
              "openid",
              "profile",
              "email",
              "api",
              "roles",
              "account"
            ],
            "RequirePkce": false,
            "RequireConsent": false,
            "RequireClientSecret": false,
            "AccessTokenLifetime": 7200,
            "IdentityTokenLifetime": 7200
          },
          {
            "ClientId": "chronos",
            "ClientName": "chronos",
            "AllowedGrantTypes": [ "authorization_code" ],
            "RedirectUris": [
              "https://chronos.{{ .Values.portal.zooUrl }}/authentication/login-callback",
              "https://chronos.{{ .Values.portal.zooUrl }}/assets/auth/silent-callback.html",
              "https://chronos.{{ .Values.portal.zooUrl }}/swagger/oauth2-redirect.html",
              "https://pile-turner.chronos.{{ .Values.portal.zooUrl }}/authentication/login-callback",
              "https://pile-turner.chronos.{{ .Values.portal.zooUrl }}/swagger/oauth2-callback.html"
            ],
            "PostLogoutRedirectUris": [
              "https://chronos.{{ .Values.portal.zooUrl }}/authentication/logout-callback",
              "https://pile-turner.chronos.{{ .Values.portal.zooUrl }}/authentication/logout-callback"
            ],
            "AllowedScopes": [
              "openid",
              "profile",
              "email",
              "api",
              "roles"
            ],
            "RequirePkce": false,
            "RequireConsent": false,
            "RequireClientSecret": false,
            "AccessTokenLifetime": 7200,
            "IdentityTokenLifetime": 7200
          },
          {
            "ClientId": "chronos-live",
            "ClientName": "chronos-live",
            "AllowedGrantTypes": [ "authorization_code" ],
            "RedirectUris": [
              "https://live.chronos.{{ .Values.portal.zooUrl }}/authentication/login-callback",
              "https://live.chronos.{{ .Values.portal.zooUrl }}/assets/auth/silent-callback.html"
            ],
            "PostLogoutRedirectUris": [
              "https://live.chronos.{{ .Values.portal.zooUrl }}/authentication/logout-callback"
            ],
            "AllowedScopes": [
              "openid",
              "profile",
              "email",
              "api",
              "roles"
            ],
            "RequirePkce": false,
            "RequireConsent": false,
            "RequireClientSecret": false,
            "AccessTokenLifetime": 7200,
            "IdentityTokenLifetime": 7200
          }
        ]
      },
      "AuthenticatorConfiguration": [
        {
          "Order": 1,
          "Enabled": true,
          "Type": 0
        },
        {
          "Order": 2,
          "Enabled": {{ .Values.portal.ldap.enable }},
          "Type": 1
        }
      ],
      "LdapConfigurations": [
        {
          "Host": "{{ .Values.portal.ldap.host }}",
          "Username": "{{ .Values.portal.ldap.domain }}\\{{ .Values.portal.ldap.username }}",
          "Password": "{{ .Values.portal.ldap.password }}",
          "BaseDN": "{{ .Values.portal.ldap.baseDN }}",
          "UserNameAttribute": "{{ .Values.portal.ldap.userNameAttribute }}",
          "FirstNameAttribute": "{{ .Values.portal.ldap.firstNameAttribute }}",
          "LastNameAttribute": "{{ .Values.portal.ldap.lastNameAttribute }}",
          "EmailAttribute": "{{ .Values.portal.ldap.emailAttribute }}",
          "Port": {{ .Values.portal.ldap.port }},
          "SecureSocketLayer": {{ .Values.portal.ldap.secureSocketLayer }},
          "Domain": "{{ .Values.portal.ldap.domain }}",
          "MemberOfAttribute": "{{ .Values.portal.ldap.memberOf }}",
          "GroupFilter": "{{ .Values.portal.ldap.groupFilter }}"
        }
      ],
      "SeedMode": {
        "SeedConfig": "CreateIfNotExists" // None ---> Stay as is, CreateIfNotExists ----> create if not exists Reset ---> Clear and Re-Create
      }
    }