apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}-portal-webapp-service
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    portal/component: portal-webapp
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "portal.selectorLabels" . | nindent 4 }}
    portal/component: portal-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}-portal-webapp
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    portal/component: portal-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}
      portal/component: portal-webapp
  template:
    metadata:
      labels:
        {{- include "portal.selectorLabels" . | nindent 8 }}
        portal/component: portal-webapp
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ template "portal.fullname" . }}-portal-webapp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryBase }}/cit-dev/mes/portal/synit.portal.webapp:test"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html/assets/appConfig.json
              name: {{ template "portal.fullname" . }}-webapp-conf
              subPath: appConfig.json
      volumes:
      - configMap:
          name: {{ template "portal.fullname" . }}-webapp-conf
          optional: false
        name: {{ template "portal.fullname" . }}-webapp-conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}