apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}-portal-api
  namespace: portal
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    portal/component: portal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}
      portal/component: portal-api
  template:
    metadata:
      labels:
        {{- include "portal.selectorLabels" . | nindent 8 }}
        portal/component: portal-api
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-portal-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "nexus.syn-group.com/synit.portal.api:develop"
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}