apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-api
  namespace: portal
spec:
  replicas: 1
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-portal-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "nexus.mmk.mmdom.net/cit-dev/mes/portal/synit.portal.api:latest"
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}