{{- $fullName := include "portal.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-portal-authenticator
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    portal/component: portal-authenticator
spec:
  rules:
    - host: portal-authenticator.kubi.syngroup.loc
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-portal-authenticator-service
              servicePort: 80
