{{- $fullName := include "portal.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-portal-authenticator
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    portal/component: portal-authenticator
  annotations:
    cert-manager.io/cluster-issuer: mm-acme
    kubernetes.io/tls-acme: true
spec:
  rules:
    - host: portal.zoo.{{ .Values.global.locationId }}.mmk.mmdom.net
      http:
        paths:
          - path: /authenticator
            backend:
              serviceName: {{ $fullName }}-portal-authenticator-service
              servicePort: 80
  tls:
  - hosts:
    - portal.zoo.{{ .Values.global.locationId }}.mmk.mmdom.net
    secretName: portal.zoo.{{ .Values.global.locationId }}.mmk.mmdom.net