{{- $fullName := include "portal.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-portal-webapp
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    portal/component: portal-webapp
  annotations:
    cert-manager.io/cluster-issuer: mm-acme
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: portal.{{ .Values.portal.zooUrl }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-portal-webapp-service
              servicePort: 8080
  tls:
  - hosts:
    - portal.{{ .Values.portal.zooUrl }}
    secretName: portal.{{ .Values.portal.zooUrl }}