{{- $fullName := include "portal.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-portal-webapp
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    portal/component: portal-webapp
spec:
  rules:
    - host: {{ .Values.portal.baseUrl }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-portal-webapp-service
              servicePort: 8080
