apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}-portal-api-service
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    portal/component: portal-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "portal.selectorLabels" . | nindent 4 }}
    portal/component: portal-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}-portal-api
  namespace: portal
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    portal/component: portal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}
      portal/component: portal-api
  template:
    metadata:
      labels:
        {{- include "portal.selectorLabels" . | nindent 8 }}
        portal/component: portal-api
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-portal-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryBase }}/synit.portal.api:latest"
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/appsettings.Production.json
              name: {{ .Chart.Name }}-api-conf
              subPath: appsettings.Production.json
      volumes:
      - configMap:
          name: {{ .Chart.Name }}-api-conf
          optional: false
        name: {{ .Chart.Name }}-api-conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}