{{- $fullName := include "portal.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-portal-api
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    portal/component: portal-api
spec:
  rules:
    - host: {{ .Values.portal.baseUrl }}/backend
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-portal-api-service
              servicePort: 80
