apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "portal.fullname" . }}-api-conf
  labels:
    {{- include "portal.labels" . | nindent 4 }}
data:
  appsettings.Production.json: |-
    {
      "Serilog": {
        "MinimumLevel": "Information",
        "WriteTo": [
          {
            "Name": "Console",
            "Args": { "outputTemplate": "[{Timestamp:HH:mm:ss.fff}] {Level:u3} - {Message}{NewLine}{Exception}" }
          },
          {
            "Name": "RollingFile",
            "Args": {
              "pathFormat": "Logs\\log-{Date}.log",
              "outputTemplate": "[{Timestamp:dd/MM/yy HH:mm:ss.fff z}] {Level:u3} {Message}{NewLine}{Exception}"
            }
          }
        ],
        "Enrich": [ "FromLogContext" ]
      },
      "Database": {
        "Name": "portal",
        "Host": "portal-mariadb",
        "Port": 3306,
        "User": "root",
        "Password": "{{ .Values.mariadb.rootUser.password }}"
      },
      "Authorization": {
        "Host": "http://{{ .Chart.Name }}-portal-authenticator-service",
        "Issuer": "http://{{ .Values.portal.baseUrl }}/authenticator"
      },
      "Menu": {
        "GroupMenuItems": [
          {
            "Id": 1,
            "Title": "Main Keep"
          },
          {
            "Id": 2,
            "Title": "Group1",
            "GroupMenuItemId": 1,
            "Tooltip": "I am a tooltip!"
          }
        ],
        "AppMenuItems": [
          {
            "Id": 3,
            "Title": "App1",
            "Url": "http://www.example.com",
            "GroupMenuItemId": 2,
            "Tooltip": "and on apps!"
          }
        ]
      },
      "Theme": {
        "Themes": [
          {
            "Id": 1,
            "Title": "Syn IT Light",
            "PrimaryHexValue": "#bf360c",
            "PrimaryLightHexValue": "#f9683a",
            "SecondaryHexValue": "#37474f",
            "SecondaryLightHexValue": "#62727b",
            "IsDarkTheme": false,
            "LogoSvg": "<path d=\"M11.5,0.5C12,0.75 13,2.4 13,3.5C13,4.6 12.33,5 11.5,5C10.67,5 10,4.85 10,3.75C10,2.65 11,2 11.5,0.5M18.5,9C21,9 23,11 23,13.5C23,15.06 22.21,16.43 21,17.24V23H12L3,23V17.24C1.79,16.43 1,15.06 1,13.5C1,11 3,9 5.5,9H10V6H13V9H18.5M12,16A2.5,2.5 0 0,0 14.5,13.5H16A2.5,2.5 0 0,0 18.5,16A2.5,2.5 0 0,0 21,13.5A2.5,2.5 0 0,0 18.5,11H5.5A2.5,2.5 0 0,0 3,13.5A2.5,2.5 0 0,0 5.5,16A2.5,2.5 0 0,0 8,13.5H9.5A2.5,2.5 0 0,0 12,16Z\"></path>",
            "ViewBox": "0 0 24 24",
            "IsActive": true,
            "PageTitle": "Your Portal",
            "LogoIsVector": true
          },
          {
            "Id": 2,
            "Title": "Syn IT Dark",
            "PrimaryHexValue": "#bf360c",
            "PrimaryLightHexValue": "#f9683a",
            "SecondaryHexValue": "#90a4ae",
            "SecondaryLightHexValue": "#c1d5e0",
            "IsDarkTheme": true,
            "LogoSvg": "<path d=\"M11.5,0.5C12,0.75 13,2.4 13,3.5C13,4.6 12.33,5 11.5,5C10.67,5 10,4.85 10,3.75C10,2.65 11,2 11.5,0.5M18.5,9C21,9 23,11 23,13.5C23,15.06 22.21,16.43 21,17.24V23H12L3,23V17.24C1.79,16.43 1,15.06 1,13.5C1,11 3,9 5.5,9H10V6H13V9H18.5M12,16A2.5,2.5 0 0,0 14.5,13.5H16A2.5,2.5 0 0,0 18.5,16A2.5,2.5 0 0,0 21,13.5A2.5,2.5 0 0,0 18.5,11H5.5A2.5,2.5 0 0,0 3,13.5A2.5,2.5 0 0,0 5.5,16A2.5,2.5 0 0,0 8,13.5H9.5A2.5,2.5 0 0,0 12,16Z\"></path>",
            "ViewBox": "0 0 24 24",
            "IsActive": false,
            "PageTitle": "Your Portal",
            "UseBrightColors": true,
            "LogoIsVector": true
          }
        ]
      }
    }