apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "forecast-tracker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "forecast-tracker.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "forecast-tracker.labels" . | nindent 4 }}
    forecast-tracker/component: {{ .Release.Name }}-service
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "forecast-tracker.selectorLabels" . | nindent 6 }}
      forecast-tracker/component: {{ .Release.Name }}-service
  template:
    metadata:
      labels:
        {{- include "forecast-tracker.selectorLabels" . | nindent 8 }}
        forecast-tracker/component: {{ .Release.Name }}-service
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Release.Name }}-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryBase }}/cit-dev/services/forecast-tracker/mm.synforecast.backend:latest"
          imagePullPolicy: Always
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: LOGGING_LEVEL_WEB
            value: "INFO"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "{{ .Values.mariadb.db.password }}"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://{{ .Release.Name }}-mariadb:3306/{{ .Values.mariadb.db.name }}?useUnicode=true&characterEncoding=utf8&useSSL=false"
          - name: SPRING_DATASOURCE_USERNAME
            value: "{{ .Values.mariadb.db.user }}"
          - name: SPRING_RABBITMQ_ADDRESSES
            value: rabbitmq-ha.infra.{{ .Values.forecasttracker.zooUrl }} 
          - name: SPRING_RABBITMQ_PASSWORD
            value: {{ .Values.rabbitmq.password }} 
          - name: SPRING_RABBITMQ_USERNAME
            value: {{ .Values.rabbitmq.username }} 
          - name: VALIDATION_ERRORS_QUEUE
            value: "{{ .Release.Name }}.validation_error"
          - name: VALIDATION_START_QUEUE
            value: "{{ .Release.Name }}.validation_start"
          - name: WORKFLOW_RETURN_QUEUE
            value: "{{ .Release.Name }}.knime_output"
          - name: WORKFLOW_START_QUEUE
            value: "{{ .Release.Name }}.knime_start"
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}