apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webapp
  labels:
    {{- include "forecast-tracker.labels" . | nindent 4 }}-webapp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "forecast-tracker.selectorLabels" . | nindent 4 }}
    forecast-tracker/component: {{ .Release.Name }}-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp
  labels:
    {{- include "forecast-tracker.labels" . | nindent 4 }}
    forecast-tracker/component: {{ .Release.Name }}-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "forecast-tracker.selectorLabels" . | nindent 6 }}
      forecast-tracker/component: {{ .Release.Name }}-webapp
  template:
    metadata:
      labels:
        {{- include "forecast-tracker.selectorLabels" . | nindent 8 }}
        forecast-tracker/component: {{ .Release.Name }}-webapp
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Release.Name }}-webapp
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryBase }}/cit-dev/services/forecast-tracker/mm.synforecast.frontend:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}