apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "forecast-tracker.labels" . | nindent 4 }}
    forecast-tracker/component: {{ .Release.Name }}-service
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    cert-manager.io/cluster-issuer: mm-acme
    kubernetes.io/tls-acme: true
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.forecasttracker.zooUrl }}
      http:
        paths:
          - path: /api
            backend:
              serviceName: {{ .Release.Name }}-service
              servicePort: 8888
          - path: /actuator
            backend:
              serviceName: {{ .Release.Name }}-service
              servicePort: 8888