apiVersion: v1
kind: Service
metadata:
  name: {{ include "forecast-tracker.fullname" . }}
  labels:
    {{- include "forecast-tracker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "forecast-tracker.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-tracker-service
  labels:
    {{- include "forecast-tracker.labels" . | nindent 4 }}
    panda/component: forecast-tracker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "forecast-tracker.selectorLabels" . | nindent 6 }}
      panda/component: forecast-tracker-service
  template:
    metadata:
      labels:
        {{- include "forecast-tracker.selectorLabels" . | nindent 8 }}
        panda/component: forecast-tracker-service
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-forecast-tracker-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryBase }}/cit-dev/services/forecast-tracker/mm.synforecast.backend:latest"
          imagePullPolicy: Always
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: LOGGING_LEVEL_WEB
            value: "INFO"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "forecast_pass"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://{{ include "forecast-tracker.fullname" . }}-forecast-tracker-db:3306/jfc_mgmt?useUnicode=true&characterEncoding=utf8&useSSL=false"
          - name: SPRING_DATASOURCE_USERNAME
            value: "forecast_user"
          - name: SPRING_RABBITMQ_ADDRESSES
            value: "forecasttracker"
          - name: VALIDATION_ERRORS_QUEUE
            value: "validation_errors_fct_regjoz"
          - name: VALIDATION_START_QUEUE
            value: "ValidationInput"
          - name: WORKFLOW_RETURN_QUEUE
            value: "knime_output_fct_regjoz"
          - name: WORKFLOW_START_QUEUE
            value: "Knime"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}