apiVersion: v1
kind: Service
metadata:
  name: {{ include "forecast-tracker.fullname" . }}-phpmyadmin
  labels:
    {{- include "forecast-tracker.labels" . | nindent 4 }}
    forecast-tracker/component: phpmyadmin
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "forecast-tracker.selectorLabels" . | nindent 4 }}
    forecast-tracker/component: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forecast-tracker.fullname" . }}-phpmyadmin
  labels:
    {{- include "forecast-tracker.labels" . | nindent 4 }}
    forecast-tracker/component: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "forecast-tracker.selectorLabels" . | nindent 6 }}
      forecast-tracker/component: phpmyadmin
  template:
    metadata:
      labels:
        {{- include "forecast-tracker.selectorLabels" . | nindent 8 }}
        forecast-tracker/component: phpmyadmin
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-phpmyadmin
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "docker.io/bitnami/phpmyadmin:5.0.2-debian-10-r126"
          imagePullPolicy: Always
          env:
          - name: DATABASE_HOST
            value: "{{ include "forecast-tracker.fullname" . }}-mariadb"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}