{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mm-pandaconfigurator-webapp.serviceAccountName" . }}
  labels:
{{ include "mm-pandaconfigurator-webapp.labels" . | nindent 4 }}
{{- end -}}
