{{- $fullName := include "infra.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-minio-admin
  labels:
    {{- include "infra.labels" . | nindent 4 }}
    infra/component: infra-minio
  annotations:
    cert-manager.io/cluster-issuer: mm-acme
spec:
  rules:
    - host: minio.zoo.{{ .Values.global.locationId }}.mmk.mmdom.net
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-minio
              servicePort: 9000
  tls:
  - hosts:
    - minio.zoo.{{ .Values.global.locationId }}.mmk.mmdom.net
    secretName: minio.zoo.{{ .Values.global.locationId }}.mmk.mmdom.net