apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra.fullname" . }}-rabbitmq-node-port
  labels:
    {{- include "infra.labels" . | nindent 4 }}
    infra/component: rabbitmq-ha
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: amqp
    nodePort: 30102
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: amqps
    nodePort: 30101
    port: 5671
    protocol: TCP
    targetPort: 5671
  selector:
    app: rabbitmq-ha
    release: infra
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}